Corrected husky pre-commit

diff --git a/.husky/_/pre-commit b/.husky/_/pre-commit
--- a/.husky/_/pre-commit
+++ b/.husky/_/pre-commit
@@ -1,2 +1,14 @@
-#!/usr/bin/env sh
-. "$(dirname "$0")/h"
+#!/bin/sh
+. "$(dirname "$0")/_/husky.sh"
+
+echo "Lint-staged command start..."
+
+npx lint-staged
+
+echo "Starting Cypress tests..."
+npm run test:e2e
+
+if [ $? -ne 0 ]; then
+  echo "Cypress tests failed. Please fix the errors before committing."
+  exit 1
+fi
